# Generated by Django 6.0.3 on 2026-04-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interest_embedding',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest_tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='knowledge_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='view_time_minutes',
        ),
    ]
