# Generated by Django 6.0.3 on 2026-04-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_interest_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interest_embedding',
        ),
    ]
