# Generated by Django 5.2.12 on 2026-04-06 10:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='관심 키워드')),
                ('knowledge_level', models.CharField(blank=True, choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], max_length=20, null=True, verbose_name='지식 수준')),
                ('view_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='관람 희망 시간(분)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '세션',
                'verbose_name_plural': '세션 목록',
                'db_table': 'sessions',
            },
        ),
    ]
