# Generated by Django 6.0.3 on 2026-04-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_session_history_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='현재 위치(전시실)'),
        ),
    ]
