# Generated by Django 6.0.3 on 2026-04-07 05:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0004_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='interest_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, verbose_name='관심도 임베딩'),
        ),
    ]
