# Generated by Django 5.2.12 on 2026-04-06 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.IntegerField(verbose_name='유물 ID')),
                ('feedback_type', models.CharField(choices=[('like', '흥미로워요'), ('dislike', '별로예요'), ('why', '왜 이거예요?'), ('similar', '비슷한 작품'), ('short_route', '짧은 경로')], max_length=20, verbose_name='피드백 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='user_sessions.session', verbose_name='세션')),
            ],
            options={
                'verbose_name': '피드백',
                'verbose_name_plural': '피드백 목록',
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', '큐레이터')], max_length=10, verbose_name='역할')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('artifact_id', models.IntegerField(blank=True, null=True, verbose_name='추천 유물 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_sessions.session', verbose_name='세션')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지 목록',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
    ]
