# Generated by Django 6.0.3 on 2026-04-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_feedback_id_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('viewed', '관람완료'), ('like', '흥미로워요'), ('dislike', '별로예요'), ('why', '왜 이거예요?'), ('similar', '비슷한 작품'), ('short_route', '짧은 경로')], max_length=20, verbose_name='피드백 유형'),
        ),
    ]
