# Generated by Django 6.0.3 on 2026-04-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_feedback_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('like', '좋아요'), ('dislike', '싫어요')], max_length=20, verbose_name='피드백 유형'),
        ),
    ]
