# Generated by Django 5.2.12 on 2026-04-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleveland_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('collection', models.CharField(blank=True, max_length=200)),
                ('technique', models.CharField(blank=True, max_length=200)),
                ('culture', models.JSONField(blank=True, default=list)),
                ('creation_date_earliest', models.IntegerField(blank=True, null=True)),
                ('creation_date_latest', models.IntegerField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('did_you_know', models.TextField(blank=True)),
                ('embedding_text', models.TextField(blank=True)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '유물',
                'verbose_name_plural': '유물 목록',
                'db_table': 'artifacts',
                'ordering': ['cleveland_id'],
            },
        ),
    ]
