# Generated by Django 6.0.3 on 2026-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleveland_id', models.IntegerField(unique=True)),
                ('accession_number', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('tombstone', models.TextField(blank=True)),
                ('creation_date', models.CharField(blank=True, max_length=100)),
                ('creation_date_earliest', models.IntegerField(blank=True, null=True)),
                ('creation_date_latest', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('collection', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('technique', models.CharField(blank=True, max_length=200)),
                ('culture', models.JSONField(blank=True, default=list)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_url_full', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('did_you_know', models.TextField(blank=True)),
                ('measurements', models.CharField(blank=True, max_length=300)),
                ('share_license_status', models.CharField(blank=True, max_length=50)),
                ('embedding_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cleveland_id'],
            },
        ),
    ]
