# Generated by Django 6.0.3 on 2026-04-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
