# Generated by Django 6.0.3 on 2026-04-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_artifact_embedding_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='accession_number',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='image_url_full',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='measurements',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='share_license_status',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='tombstone',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='updated_at',
        ),
    ]
