# Generated by Django 6.0.3 on 2026-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_alter_artifact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artifact',
            name='share_license_status',
            field=models.CharField(default='CC0', max_length=20),
        ),
    ]
