# Generated by Django 6.0.3 on 2026-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_artifact_is_active_artifact_share_license_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='accession_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='artifact',
            name='creation_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artifact',
            name='measurements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='tombstone',
            field=models.TextField(blank=True),
        ),
    ]
