# Generated by Django 6.0.3 on 2026-04-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_remove_artifact_accession_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='artists_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='artifact',
            name='series',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
