# Generated by Django 6.0.3 on 2026-04-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0004_artifact_accession_number_artifact_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='updated_at',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
