# Generated by Django 6.0.3 on 2026-04-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0004_artifact_artists_tags_artifact_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='artists_tags',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='series',
        ),
    ]
