# Generated by Django 6.0.3 on 2026-04-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_remove_artifact_artists_tags_remove_artifact_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='creation_date',
        ),
    ]
