# Generated by Django 6.0.3 on 2026-04-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_artifact_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='collection',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='current_location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='department',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='technique',
            field=models.TextField(blank=True),
        ),
    ]
