# Generated by Django 6.0.3 on 2026-04-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_alter_artifact_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='accession_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='creation_date',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
