# Generated by Django 5.2.12 on 2026-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_remove_artifact_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
