# Generated by Django 6.0.3 on 2026-04-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0007_alter_artifact_accession_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='title',
            field=models.TextField(),
        ),
    ]
