# Generated by Django 6.0.3 on 2026-04-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0009_artifact_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='did_you_know',
        ),
    ]
