# Generated by Django 6.0.3 on 2026-04-06 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0008_alter_artifact_image_url_alter_artifact_title'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_histories', to='artifacts.artifact')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_histories', to='sessions.session')),
            ],
            options={
                'db_table': 'view_history',
                'ordering': ['-visited_at'],
            },
        ),
    ]
