# Generated by Django 6.0.3 on 2026-04-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewHistory',
        ),
    ]
